### ISSUE TITLE
help with too many errors

### ISSUE THREAD

**Issue by Thoky81** [Ed-EE-Eng/Spool_Scale_Project#1]
Hi,

could you please advice why I am getting these errors?
Thanks

__Arduino: 1.8.10 (Mac OS X), Board: "Arduino Nano, ATmega328P"

SpoolScale_VER1_07:41:80: error: no matching function for call to 'LiquidCrystal_I2C::LiquidCrystal_I2C(int, int, int, int, int, int, int, int)'
 LiquidCrystal_I2C lcd(I2C_ADDR,En_pin,Rw_pin,Rs_pin,D4_pin,D5_pin,D6_pin,D7_pin);
                                                                                ^
In file included from /Users/Thoky/Documents/Arduino/Projects/Spool_Scale_Project-master/examples/SpoolScale_VER1_07/SpoolScale_VER1_07.ino:15:0:
/Users/Thoky/Documents/Arduino/libraries/Arduino-LiquidCrystal-I2C-library-master/LiquidCrystal_I2C.h:71:2: note: candidate: LiquidCrystal_I2C::LiquidCrystal_I2C(uint8_t, uint8_t, uint8_t, uint8_t)
  LiquidCrystal_I2C(uint8_t lcd_addr, uint8_t lcd_cols, uint8_t lcd_rows, uint8_t charsize = LCD_5x8DOTS);
  ^~~~~~~~~~~~~~~~~
/Users/Thoky/Documents/Arduino/libraries/Arduino-LiquidCrystal-I2C-library-master/LiquidCrystal_I2C.h:71:2: note:   candidate expects 4 arguments, 8 provided
/Users/Thoky/Documents/Arduino/libraries/Arduino-LiquidCrystal-I2C-library-master/LiquidCrystal_I2C.h:60:7: note: candidate: constexpr LiquidCrystal_I2C::LiquidCrystal_I2C(const LiquidCrystal_I2C&)
 class LiquidCrystal_I2C : public Print {
       ^~~~~~~~~~~~~~~~~
/Users/Thoky/Documents/Arduino/libraries/Arduino-LiquidCrystal-I2C-library-master/LiquidCrystal_I2C.h:60:7: note:   candidate expects 1 argument, 8 provided
/Users/Thoky/Documents/Arduino/libraries/Arduino-LiquidCrystal-I2C-library-master/LiquidCrystal_I2C.h:60:7: note: candidate: constexpr LiquidCrystal_I2C::LiquidCrystal_I2C(LiquidCrystal_I2C&&)
/Users/Thoky/Documents/Arduino/libraries/Arduino-LiquidCrystal-I2C-library-master/LiquidCrystal_I2C.h:60:7: note:   candidate expects 1 argument, 8 provided
/Users/Thoky/Documents/Arduino/Projects/Spool_Scale_Project-master/examples/SpoolScale_VER1_07/SpoolScale_VER1_07.ino: In function 'void setup()':
SpoolScale_VER1_07:1969:16: error: no matching function for call to 'LiquidCrystal_I2C::begin(int, int)'
  lcd.begin(20,4);               // initialize the lcd
                ^
In file included from /Users/Thoky/Documents/Arduino/Projects/Spool_Scale_Project-master/examples/SpoolScale_VER1_07/SpoolScale_VER1_07.ino:15:0:
/Users/Thoky/Documents/Arduino/libraries/Arduino-LiquidCrystal-I2C-library-master/LiquidCrystal_I2C.h:76:7: note: candidate: void LiquidCrystal_I2C::begin()
  void begin();
       ^~~~~
/Users/Thoky/Documents/Arduino/libraries/Arduino-LiquidCrystal-I2C-library-master/LiquidCrystal_I2C.h:76:7: note:   candidate expects 0 arguments, 2 provided
SpoolScale_VER1_07:1972:6: error: 'class LiquidCrystal_I2C' has no member named 'setBacklightPin'; did you mean 'setBacklight'?
  lcd.setBacklightPin(BACKLIGHT_PIN,POSITIVE);
      ^~~~~~~~~~~~~~~
      setBacklight
SpoolScale_VER1_07:1972:36: error: 'POSITIVE' was not declared in this scope
  lcd.setBacklightPin(BACKLIGHT_PIN,POSITIVE);
                                    ^~~~~~~~
Multiple libraries were found for "HX711.h"
 Used: /Users/Thoky/Documents/Arduino/libraries/HX711_Arduino_Library
Multiple libraries were found for "EEPROM.h"
 Used: /Users/Thoky/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/libraries/EEPROM
Multiple libraries were found for "Encoder.h"
 Used: /Users/Thoky/Documents/Arduino/libraries/Encoder
Multiple libraries were found for "Wire.h"
 Used: /Users/Thoky/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/libraries/Wire
Multiple libraries were found for "LiquidCrystal_I2C.h"
 Used: /Users/Thoky/Documents/Arduino/libraries/Arduino-LiquidCrystal-I2C-library-master
Multiple libraries were found for "Bounce2.h"
 Used: /Users/Thoky/Documents/Arduino/libraries/Bounce2
exit status 1
no matching function for call to 'LiquidCrystal_I2C::LiquidCrystal_I2C(int, int, int, int, int, int, int, int)'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.__

**Comment by Thoky81** [comment]
ok I made some changes. I uncommented this:
 //	lcd.setBacklightPin(BACKLIGHT_PIN,POSITIVE);

and cleaned up the libraries but now after the upload is ok I am getting this:

Could you please advice how to fix it?

Thanks a lot

Program Started: SpoolScale_VER1.07
	  Mar 23 2020
	  22:35:10
At Power-up (BEFORE CalCfg_ACTIVE = CalCfg_DEFAULT)...
Dump:	CalCfg_DEFAULT	CalCfg_ACTIVE
     StructRev: AMC1		
 Ld_Cell Scale: 392582.4062	0.0000
Ld_Cell Offset: -157616.00	0.00
Ld_Cell Filter: 0.80	0.00
 Last Spool Wt: 125.00		0.00
     Last Fnum: 1		0
     Len Units: 0		0
      Wt Units: 0		0

        #Bytes: 24		24
      CRC(HEX): 3C1B8F49	8E9CD89B
Before EEPROM Read (AFTER CalCfg_ACTIVE = CalCfg_DEFAULT)......
Dump:	CalCfg_DEFAULT	CalCfg_ACTIVE
     StructRev: AMC1		AMC1
 Ld_Cell Scale: 392582.4062	392582.4062
Ld_Cell Offset: -157616.00	-157616.00
Ld_Cell Filter: 0.80	0.80
 Last Spool Wt: 125.00		125.00
     Last Fnum: 1		1
     Len Units: 0		0
      Wt Units: 0		0

        #Bytes: 24		24
      CRC(HEX): 3C1B8F49	3C1B8F49
Reading CalCfg Data from EEPROM...Read AFTER EEPROM READ...
****************READ MODE - Called with CheckOnly = false
Checking and Fetching CalCfg data from EEPROM....Check #1 - Calc directly from EPROM: 8E9CD89B
                CRC Stored in EPROM: 0
                        CRC Results: CRC DOES NOT MATCH - Data No Good!
EEPROM REV CODE DIDN'T MATCH!!!
 RevCode Check - EEPROM/SHOULD BE: ⸮⸮ / AMC1
FAILED! 1865
*************CHECK MODE - Called with CheckOnly = true
Checking and Fetching CalCfg data from EEPROM....Check #1 - Calc directly from EPROM: 8E9CD89B
                CRC Stored in EPROM: 0
                        CRC Results: CRC DOES NOT MATCH - Data No Good!
EEPROM REV CODE DIDN'T MATCH!!!
 RevCode Check - EEPROM/SHOULD BE: B⸮�	 / AMC1
Leaving Setup.....

**Comment by Ed-EE-Eng** [comment]
Hi – Sorry I did not see your email until late yesterday but I will try to help you with the questions you have with both of your emails.

 

It looks like you have overcome the issue with your first email and your second emal shows that you have succeeded in compiling and uploading code to the nano.  Great!  The Arduino IDE and library handling is somewhat imprecise as duplication of library names by different authors confuses the library manager.  Looks like you were able to get through that problem.

 

As to your second email, the messaging you are receiving on the serial monitor is actually a series of debug print outs that I used during the development while getting the data base code working.  

 

To suppress these printouts, comment out the at line 1354.  That is, 

 

#define SetupPrintDiag

 

               Add ‘//’ at the beginning of line 1354 to turn it into

 

//#define SetupPrintDiag

 

In any event, the printouts are just CalConfig Data Base dumps at power up that compares the active data base values to 

               First power up default values, 

                              And

               Second, values that were saved into EEPROM during the most recent calibration run.

 

These printouts are ‘normal’ and are really not reporting any problems, simply the status of the active values at a few points in time within the “Setup” process.  Again, these can be suppressed by making the slight change to the #define SetupPrintDiag line.  This was “my mistake” as I should have commented out the line before I uploaded the code.  

 

In any event, once the setup code completes, the serial print outputs should be done, and you should not see any further monitor output.  The code should run properly.

 

If the code is working, you should see output on the 4x20 LCD display corresponding to the proper operation of the scale.  

 

If the LCD is not showing any display, check the following few things.

 

1)      Check the CONTRAST POT setting on the back of the LCD display (simply adjust the pot to see if the display appears,  If that does not correct things, then the I2C LCD library code is probably not getting initialized properly…check the following few things. 

 

2)      Be sure that the I2C address set in the program matches the particular LCD display you are using. The I2C addresses can vary from supplier to supplier and I have seen at least two different I2C address values over the years.  To set or change these values, look for “define I2C_ADDR” in the code.  You will see the following around line 27.

 

//Common I2C lcd address option are typically 0x38 or 0x27.  Set the value to one that matches your particular LCD display module

#define I2C_ADDR    0x27  // Define I2C Address for 20x4 LCD module

//#define I2C_ADDR    0x38  // Define I2C Address for 20x4 LCD module

 

3)      Another building reported issues with the LCD.  His comments were:

 

The software as given does not compile because the Liquidcrystal_I2C library is not as described. The article states that one should use the Liquidcrystal_I2C library that comes with the IDE, but this does not compile. There are several versions of the library that are out there, and they have different parameter calls. The code supplied makes the declaration:

 

LiquidCrystal_I2C lcd(I2C_ADDR,En_pin,Rw_pin,Rs_pin,D4_pin,D5_pin,D6_pin,D7_pin);

 

which is what you would write for a NON I2C device. The whole point of using an I2C device is to not have to deal with all the pins. Using the IDE supplied library I changed it to:

 

LiquidCrystal_I2C lcd(I2C_ADDR,20,4);

 

and it complied.

 

Also, the I2C address for my display was x3F, not one of the values supplied.

 

My suspicion is that there are multiple I2C libraries out in the universe and the call to initialize the library these libraries vary.  The one I have in my library required defining the data pins as well as the I2C address.  Other libraries seem to require the I2C address and the SIZE of the display (20 characters x 4 lines).

 

 

I hope this helps,  If you have any further questions or I can be of any further help, please feel free to contact me directly vi emal.

 

 

Best Regards

 

-         Ed

 

Edward W. Andrews

 

email:  <mailto:eandrews.amc@wi.rr.com> eandrews.amc@wi.rr.com

 

 

This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message. Thank you.

 

 

Eandrews.amc@wi.rr.com.

**Comment by Thoky81** [comment]
Hi,

I have it working 👍 👍 👍 
At the end my i2c address was also like your -> 0x3F 😀

I really appreciate your support with nice and clear explanation 👍 

Thanks again and all the best
